import Head from 'next/head';
import { Container } from '@mantine/core';
import { GetServerSideProps, InferGetServerSidePropsType } from 'next';
import { Header } from '@/components/Header';
import { getServerSideUserTopTracksProps } from '@/lib';
import { UserTopTracks, UserTopTracksProps } from '@/components/UserTopTracks';

type UserPageProps = UserTopTracksProps;

export const getServerSideProps: GetServerSideProps<UserPageProps> = async (
  context
) => {
  const id = context.params?.id;

  if (typeof id !== 'string') {
    return {
      notFound: true,
    };
  }

  const props = await getServerSideUserTopTracksProps(id);
  if (props == null) {
    return { notFound: true };
  }
  return { props };
};

export default function UserPage({
  user,
  topTracks,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>Kokage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Container my="sm">
          <UserTopTracks user={user} topTracks={topTracks} />
        </Container>
      </main>
    </>
  );
}
