import Link from 'next/link';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useMemo } from 'react';

export default function Home() {
  const router = useRouter();
  const user = useMemo((): { id?: string; name?: string } => {
    return router.query;
  }, [router.query]);

  return (
    <>
      <Head>
        <title>Kokage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {(user.id && user.name && (
          <p>
            {user.name} (id: {user.id})
          </p>
        )) || <Link href="/login">Login</Link>}
      </main>
    </>
  );
}
