import Link from 'next/link';
import Head from 'next/head';
import { useSession } from 'next-auth/react';
import { useEffect } from 'react';
import { Header } from '@/components/Header';

export default function Home() {
  const { data: session, status } = useSession();

  useEffect(() => {
    console.log({ session });
  }, [session]);

  return (
    <>
      <Head>
        <title>Kokage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        工事中！！！
      </main>
    </>
  );
}
