import Head from 'next/head';
import { Header } from '@/components/Header';
import { GetServerSideProps, InferGetServerSidePropsType } from 'next';
import { UserTopTracks, UserTopTracksProps } from '@/components/UserTopTracks';
import { getServerSideUserTopTracksProps } from '@/lib';
import { getServerSession } from 'next-auth';
import { authOptions } from './api/auth/[...nextauth]';
import { Container } from '@mantine/core';

export default function Home({
  userTopTracksProps,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>Kokage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        {userTopTracksProps && (
          <Container my="sm">
            <UserTopTracks {...userTopTracksProps} />
          </Container>
        )}
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps<{
  userTopTracksProps?: UserTopTracksProps;
}> = async (context) => {
  const session = await getServerSession(context.req, context.res, authOptions);
  if (session?.user?.id == null) {
    return {
      props: {},
    };
  }

  const props = await getServerSideUserTopTracksProps(session.user.id);
  if (props == null) {
    return { props: {} };
  }
  return {
    props: {
      userTopTracksProps: props,
    },
  };
};
